/**
 * Every gog command `main` may run in Google Workspace (KTD2), generated
 * rather than picked, so a hand-made list never keeps the assistant from
 * ordinary work in its files. The token, not this list, is the boundary.
 *
 * gog v0.43.0 takes exact command paths (`GOG_ENABLE_COMMANDS_EXACT`, where a
 * parent does not enable its children), so the list names each one:
 *
 * - every runnable command under `drive`, `docs`, `sheets`, `slides` and
 *   `forms`, and `batch`'s six, which stage and submit those products'
 *   request batches. Source: gogcli v0.43.0's `docs/commands.generated.md`,
 *   which `gog schema --json` generates. Each usage line that is not a
 *   `<command>` group gives its words up to the first argument or flag, with
 *   aliases dropped, as `commandPath` in `internal/cmd/enabled_commands.go`
 *   reads them. gog's top-level shortcuts (`gog ls`, `gog upload` and the
 *   rest) repeat Drive commands under other paths and are not listed;
 * - `slides.batch-submit` and `forms.batch-submit`, which `batch end`
 *   checks before it submits a Slides or Forms batch
 *   (`internal/cmd/batch_dispatch.go`);
 * - `api.call` and `api.describe`, and `api.<method id>`, lowercased, for
 *   every method of the Discovery documents of Drive v3 (revision 20261005),
 *   Docs v1 (20261006), Sheets v4 (20261005), Slides v1 (20261006) and Forms
 *   v1 (20261004), fetched 2026-10-09. `api call` runs a method only when
 *   both `api.call` and the method's own path are enabled
 *   (`enforceDiscoveryMethodPolicy` in `internal/cmd/api.go`); it reaches
 *   what gog has no command for, and `api describe` shows what a method takes.
 *
 * A command that calls a Google host with no agent credential is left out.
 * The gateway injects main's token only on `AGENT_GOOGLE_HOSTS` (`grant.ts`),
 * so such a command can only fail with a 401, which main's rules read as a
 * connection only the operator can restore. That leaves out `drive activity
 * query`, on driveactivity.googleapis.com, and the five `drive labels`
 * commands, on drivelabels.googleapis.com. Drive v3's own label methods,
 * `api.drive.files.listlabels` and `api.drive.files.modifylabels`, are on
 * www.googleapis.com and stay.
 *
 * Nothing else is left out by choice. When gog or an API changes, regenerate
 * the list the same way and update the counts its test pins.
 */
export const WORKSPACE_GOG_COMMANDS: readonly string[] = [
  // Drive
  'drive.audit.sharing',
  'drive.audit.user',
  'drive.bulk.remove-public',
  'drive.bulk.update-role',
  'drive.changes.list',
  'drive.changes.poll',
  'drive.changes.serve',
  'drive.changes.start-token',
  'drive.changes.stop',
  'drive.changes.watch',
  'drive.comments.create',
  'drive.comments.delete',
  'drive.comments.get',
  'drive.comments.list',
  'drive.comments.reopen',
  'drive.comments.reply',
  'drive.comments.resolve',
  'drive.comments.update',
  'drive.copy',
  'drive.delete',
  'drive.download',
  'drive.drives',
  'drive.du',
  'drive.get',
  'drive.inventory',
  'drive.ls',
  'drive.mkdir',
  'drive.move',
  'drive.permissions',
  'drive.raw',
  'drive.rename',
  'drive.revisions.get',
  'drive.revisions.list',
  'drive.search',
  'drive.share',
  'drive.shortcut.create',
  'drive.sync.push',
  'drive.tree',
  'drive.unshare',
  'drive.upload',
  'drive.url',
  // Docs
  'docs.add-tab',
  'docs.cat',
  'docs.cell-style',
  'docs.cell-update',
  'docs.clear',
  'docs.comments.add',
  'docs.comments.delete',
  'docs.comments.get',
  'docs.comments.list',
  'docs.comments.locate',
  'docs.comments.poll',
  'docs.comments.reopen',
  'docs.comments.reply',
  'docs.comments.resolve',
  'docs.copy',
  'docs.create',
  'docs.delete',
  'docs.delete-tab',
  'docs.edit',
  'docs.export',
  'docs.find-range',
  'docs.find-replace',
  'docs.footer.create',
  'docs.footer.delete',
  'docs.footer.list',
  'docs.format',
  'docs.header.create',
  'docs.header.delete',
  'docs.header.list',
  'docs.headings.list',
  'docs.images.list',
  'docs.info',
  'docs.insert',
  'docs.insert-date-chip',
  'docs.insert-file-chip',
  'docs.insert-footnote',
  'docs.insert-horizontal-rule',
  'docs.insert-image',
  'docs.insert-page-break',
  'docs.insert-person',
  'docs.insert-section-break',
  'docs.insert-table',
  'docs.list-tabs',
  'docs.named-range.create',
  'docs.named-range.delete',
  'docs.named-range.list',
  'docs.named-range.replace',
  'docs.page-layout',
  'docs.paragraphs.list',
  'docs.raw',
  'docs.rename-tab',
  'docs.replace-image',
  'docs.section-columns',
  'docs.sed',
  'docs.structure',
  'docs.suggestions.list',
  'docs.table-column-width',
  'docs.table-column.delete',
  'docs.table-column.insert',
  'docs.table-merge',
  'docs.table-row.delete',
  'docs.table-row.insert',
  'docs.table-row.pin-header',
  'docs.table-row.style',
  'docs.table-unmerge',
  'docs.tables.list',
  'docs.tabs.add',
  'docs.tabs.delete',
  'docs.tabs.list',
  'docs.tabs.rename',
  'docs.update',
  'docs.write',
  // Sheets
  'sheets.add-tab',
  'sheets.append',
  'sheets.banding.clear',
  'sheets.banding.list',
  'sheets.banding.set',
  'sheets.batch-request',
  'sheets.batch-update',
  'sheets.chart.create',
  'sheets.chart.delete',
  'sheets.chart.get',
  'sheets.chart.list',
  'sheets.chart.update',
  'sheets.clear',
  'sheets.conditional-format.add',
  'sheets.conditional-format.clear',
  'sheets.conditional-format.list',
  'sheets.copy',
  'sheets.copy-paste',
  'sheets.create',
  'sheets.datasource.add',
  'sheets.datasource.delete',
  'sheets.datasource.describe',
  'sheets.datasource.list',
  'sheets.datasource.refresh',
  'sheets.datasource.table.describe',
  'sheets.datasource.table.list',
  'sheets.datasource.table.read',
  'sheets.datasource.update',
  'sheets.delete-dimension',
  'sheets.delete-tab',
  'sheets.duplicate-tab',
  'sheets.export',
  'sheets.filter.set',
  'sheets.find-replace',
  'sheets.format',
  'sheets.freeze',
  'sheets.get',
  'sheets.insert',
  'sheets.links.get',
  'sheets.links.set',
  'sheets.merge',
  'sheets.metadata',
  'sheets.named-ranges.add',
  'sheets.named-ranges.delete',
  'sheets.named-ranges.get',
  'sheets.named-ranges.list',
  'sheets.named-ranges.update',
  'sheets.notes',
  'sheets.number-format',
  'sheets.raw',
  'sheets.read-format',
  'sheets.rename-tab',
  'sheets.reorder-tab',
  'sheets.resize-columns',
  'sheets.resize-rows',
  'sheets.table.append',
  'sheets.table.clear',
  'sheets.table.create',
  'sheets.table.delete',
  'sheets.table.get',
  'sheets.table.list',
  'sheets.unmerge',
  'sheets.update',
  'sheets.update-note',
  'sheets.validation.clear',
  'sheets.validation.get',
  'sheets.validation.set',
  // Slides, and the permission to submit a Slides batch
  'slides.add-slide',
  'slides.bullets',
  'slides.copy',
  'slides.create',
  'slides.create-from-markdown',
  'slides.create-from-template',
  'slides.delete-slide',
  'slides.duplicate-slide',
  'slides.element.alt-text',
  'slides.element.create-line',
  'slides.element.create-shape',
  'slides.element.delete',
  'slides.element.group',
  'slides.element.style',
  'slides.element.transform',
  'slides.element.ungroup',
  'slides.element.z-order',
  'slides.export',
  'slides.info',
  'slides.insert-image',
  'slides.insert-text',
  'slides.link',
  'slides.list-slides',
  'slides.locate',
  'slides.move-slide',
  'slides.new-slide',
  'slides.paragraph-style',
  'slides.raw',
  'slides.read-slide',
  'slides.replace-slide',
  'slides.replace-text',
  'slides.skip-slide',
  'slides.style-text',
  'slides.table.border.style',
  'slides.table.cell.style',
  'slides.table.column.delete',
  'slides.table.column.insert',
  'slides.table.column.size',
  'slides.table.create',
  'slides.table.merge',
  'slides.table.row.delete',
  'slides.table.row.insert',
  'slides.table.row.size',
  'slides.table.unmerge',
  'slides.thumbnail',
  'slides.unskip-slide',
  'slides.update-notes',
  'slides.batch-submit',
  // Forms, and the permission to submit a Forms batch
  'forms.add-question',
  'forms.create',
  'forms.delete-question',
  'forms.get',
  'forms.move-question',
  'forms.publish',
  'forms.questions.add',
  'forms.questions.delete',
  'forms.questions.move',
  'forms.raw',
  'forms.responses.get',
  'forms.responses.list',
  'forms.update',
  'forms.watch.create',
  'forms.watch.delete',
  'forms.watch.list',
  'forms.watch.renew',
  'forms.batch-submit',
  // Request batches for Docs, Sheets, Slides and Forms
  'batch.abort',
  'batch.begin',
  'batch.end',
  'batch.list',
  'batch.prune',
  'batch.show',
  // Discovery calls, and every method of the five APIs
  'api.call',
  'api.describe',
  // Drive API v3
  'api.drive.about.get',
  'api.drive.accessproposals.get',
  'api.drive.accessproposals.list',
  'api.drive.accessproposals.resolve',
  'api.drive.approvals.approve',
  'api.drive.approvals.cancel',
  'api.drive.approvals.comment',
  'api.drive.approvals.decline',
  'api.drive.approvals.get',
  'api.drive.approvals.list',
  'api.drive.approvals.reassign',
  'api.drive.approvals.start',
  'api.drive.apps.get',
  'api.drive.apps.list',
  'api.drive.changes.getstartpagetoken',
  'api.drive.changes.list',
  'api.drive.changes.watch',
  'api.drive.channels.stop',
  'api.drive.comments.create',
  'api.drive.comments.delete',
  'api.drive.comments.get',
  'api.drive.comments.list',
  'api.drive.comments.update',
  'api.drive.drives.create',
  'api.drive.drives.delete',
  'api.drive.drives.get',
  'api.drive.drives.hide',
  'api.drive.drives.list',
  'api.drive.drives.unhide',
  'api.drive.drives.update',
  'api.drive.files.copy',
  'api.drive.files.create',
  'api.drive.files.delete',
  'api.drive.files.download',
  'api.drive.files.emptytrash',
  'api.drive.files.export',
  'api.drive.files.generatecsetoken',
  'api.drive.files.generateids',
  'api.drive.files.get',
  'api.drive.files.list',
  'api.drive.files.listlabels',
  'api.drive.files.modifylabels',
  'api.drive.files.update',
  'api.drive.files.watch',
  'api.drive.operations.get',
  'api.drive.permissions.create',
  'api.drive.permissions.delete',
  'api.drive.permissions.get',
  'api.drive.permissions.list',
  'api.drive.permissions.update',
  'api.drive.replies.create',
  'api.drive.replies.delete',
  'api.drive.replies.get',
  'api.drive.replies.list',
  'api.drive.replies.update',
  'api.drive.revisions.delete',
  'api.drive.revisions.get',
  'api.drive.revisions.list',
  'api.drive.revisions.update',
  'api.drive.teamdrives.create',
  'api.drive.teamdrives.delete',
  'api.drive.teamdrives.get',
  'api.drive.teamdrives.list',
  'api.drive.teamdrives.update',
  // Docs API v1
  'api.docs.documents.batchupdate',
  'api.docs.documents.create',
  'api.docs.documents.get',
  // Sheets API v4
  'api.sheets.spreadsheets.batchupdate',
  'api.sheets.spreadsheets.create',
  'api.sheets.spreadsheets.developermetadata.get',
  'api.sheets.spreadsheets.developermetadata.search',
  'api.sheets.spreadsheets.get',
  'api.sheets.spreadsheets.getbydatafilter',
  'api.sheets.spreadsheets.sheets.copyto',
  'api.sheets.spreadsheets.values.append',
  'api.sheets.spreadsheets.values.batchclear',
  'api.sheets.spreadsheets.values.batchclearbydatafilter',
  'api.sheets.spreadsheets.values.batchget',
  'api.sheets.spreadsheets.values.batchgetbydatafilter',
  'api.sheets.spreadsheets.values.batchupdate',
  'api.sheets.spreadsheets.values.batchupdatebydatafilter',
  'api.sheets.spreadsheets.values.clear',
  'api.sheets.spreadsheets.values.get',
  'api.sheets.spreadsheets.values.update',
  // Slides API v1
  'api.slides.presentations.batchupdate',
  'api.slides.presentations.create',
  'api.slides.presentations.get',
  'api.slides.presentations.pages.get',
  'api.slides.presentations.pages.getthumbnail',
  // Forms API v1
  'api.forms.forms.batchupdate',
  'api.forms.forms.create',
  'api.forms.forms.get',
  'api.forms.forms.responses.get',
  'api.forms.forms.responses.list',
  'api.forms.forms.setpublishsettings',
  'api.forms.forms.watches.create',
  'api.forms.forms.watches.delete',
  'api.forms.forms.watches.list',
  'api.forms.forms.watches.renew',
];
